image: rockylinux/9
secrets:
  - 2a951cc8-a728-4dfc-947f-63fdb66e8fee
triggers:
  - action: email
    condition: failure
    to: Haowen Liu <lhw@lunacd.com>
tasks:
  - setup: |
      sudo dnf module enable -y nodejs:20
      sudo dnf install -y nodejs
      sudo npm i -g corepack
  - deploy: |
      cd vision-venture
      set +x
      source ~/.vercel_token
      VERCEL_ORG_ID=team_cX2DGRRDIeD5jk2kEnkGcygj VERCEL_PROJECT_ID=prj_AjN8RwA3ehlNIhvxl9n45YQiBj3p \
        yarn dlx -q vercel -t $VERCEL_TOKEN --yes --prod
      set -x
