image: rockylinux/9
secrets:
  - 5c4d163b-247a-42ef-a017-f58c7494fd92
triggers:
  - action: email
    condition: failure
    to: Haowen Liu <lhw@lunacd.com>
tasks:
  - mirror: |
      cd vision-venture
      git remote add mirror git@github.com:andyliuhaowen/vision-venture.git
      GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no"' git push --mirror mirror
